module "main" {
  source = "../../"

  enabled                  = var.enabled
  environment_type         = var.environment_type
  cloud_provider           = var.cloud_provider
  namespace                = var.namespace
  name                     = var.name
  environment              = var.environment
  environment_name         = var.environment_name
  tag_prefix               = var.tag_prefix
  itsm_platform            = var.itsm_platform
  itsm_project_code        = var.itsm_project_code
  cost_center              = var.cost_center
  product                  = var.product
  product_owners           = var.product_owners
  code_owners              = var.code_owners
  data_owners              = var.data_owners
  availability             = var.availability
  deployer                 = var.deployer
  deletion_date            = var.deletion_date
  confidentiality          = var.confidentiality
  data_regs                = var.data_regs
  security_review          = var.security_review
  privacy_review           = var.privacy_review
  additional_tags          = var.additional_tags
  additional_data_tags     = var.additional_data_tags
  source_repo_tags_enabled = var.source_repo_tags_enabled
}
