module "main" {
  source = "../../"

  enabled                  = var.enabled
  environment_type         = var.environment_type
  cloud_provider           = var.cloud_provider
  namespace                = var.namespace
  name                     = var.name
  environment              = var.environment
  environment_name         = var.environment_name
  tag_prefix               = var.tag_prefix
  pm_platform              = var.pm_platform
  pm_project_code          = var.pm_project_code
  cost_center              = var.cost_center
  product_owners           = var.product_owners
  code_owners              = var.code_owners
  data_owners              = var.data_owners
  availability             = var.availability
  managedby                = var.managedby
  deletion_date            = var.deletion_date
  sensitivity              = var.sensitivity
  data_regs                = var.data_regs
  security_review          = var.security_review
  privacy_review           = var.privacy_review
  additional_tags          = var.additional_tags
  additional_data_tags     = var.additional_data_tags
  source_repo_tags_enabled = var.source_repo_tags_enabled
  system_prefixes_enabled  = var.system_prefixes_enabled
  owner_tags_enabled       = var.owner_tags_enabled
  itsm_platform            = var.itsm_platform
  itsm_system_id           = var.itsm_system_id
  itsm_component_id        = var.itsm_component_id
  itsm_instance_id         = var.itsm_instance_id
}
